volumes:
  pintrip:
    external: true
  pg-admin:
    external: true
services:
  fastapi:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      CORS_HOST: http://localhost:3000
      SIGNING_KEY: Hobbit
      DATABASE_URL: postgresql://pintrip:pintrip@data/pintrip
      WAIT_HOSTS: data:5432
      PORT: 8000
  data:
    build:
      context: data
      dockerfile: Dockerfile.dev
    volumes:
      - ./pintrip:/var/lib/postgresql/:data
    environment:
      POSTGRES_PASSWORD: pintrip
      POSTGRES_USER: pintrip
      POSTGRES_DB: pintrip
    ports:
      - "15432:5432"
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_API_HOST: http://localhost:8000
  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - ./pg-admin:/var/lib/pgadmin4
    ports:
      - "8082:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DISABLE_POSTFIX: 1
