FROM postgres:14.2-bullseye
COPY pintrip.sql /docker-entrypoint-initdb.d
RUN chmod a+r /docker-entrypoint-initdb.d/*

# NOTE CHANGE THE ABOVE AS IT WAS JUST COPIED AND PASTED

# If you're using a relational database and want migrations
# to be run automatically, delete the previous CMD line and
# uncomment this CMD line
# CMD /wait && python -m migrations up && uvicorn main:app --reload --host 0.0.0.0
